config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get 'admin/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :admins, controllers: {sessions: 'admins/sessions'}


  resources :frequentquestions
    
end

app/models/frequentquestion.rb
class Frequentquestion < ApplicationRecord
end

app/controllers/frequentquestions_controller.rb
class FrequentquestionsController < ApplicationController
  before_action :set_frequentquestion, only: %i[ show edit update destroy ]
  # before_action :authenticate_admin!
   layout 'admin'
  # GET /frequentquestions or /frequentquestions.json
  def index
    @frequentquestions = Frequentquestion.all
  end

  # GET /frequentquestions/1 or /frequentquestions/1.json
  def show
  end

  # GET /frequentquestions/new
  def new
    @frequentquestion = Frequentquestion.new
  end

  # GET /frequentquestions/1/edit
  def edit
  end

  # POST /frequentquestions or /frequentquestions.json
  def create
    @frequentquestion = Frequentquestion.new(frequentquestion_params)

    respond_to do |format|
      if @frequentquestion.save
        format.html { redirect_to frequentquestion_url(@frequentquestion), notice: "Frequentquestion was successfully created." }
        format.json { render :show, status: :created, location: @frequentquestion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frequentquestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequentquestions/1 or /frequentquestions/1.json
  def update
    respond_to do |format|
      if @frequentquestion.update(frequentquestion_params)
        format.html { redirect_to frequentquestion_url(@frequentquestion), notice: "Frequentquestion was successfully updated." }
        format.json { render :show, status: :ok, location: @frequentquestion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frequentquestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequentquestions/1 or /frequentquestions/1.json
  def destroy
    @frequentquestion.destroy

    respond_to do |format|
      format.html { redirect_to frequentquestions_url, notice: "Frequentquestion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequentquestion
      @frequentquestion = Frequentquestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frequentquestion_params
      params.require(:frequentquestion).permit(:questions, :answer)
    end
end

app/helpers/frequentquestions_helper.rb
module FrequentquestionsHelper
end

app/views/frequentquestions/_form.html.erb
<%= form_with(model: frequentquestion) do |form| %>
  <% if frequentquestion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(frequentquestion.errors.count, "error") %> prohibited this frequentquestion from being saved:</h2>

      <ul>
        <% frequentquestion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :questions, style: "display: block" %>
    <%= form.text_field :questions %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_area :answer %>
  </div>
  <br>
  <div>
    <%= form.submit 'Aceptar'%>
  </div>
<% end %>

app/views/frequentquestions/_frequentquestion.html.erb
<div id="<%= dom_id frequentquestion %>">
  <p>
    <strong>Questions:</strong>
    <%= frequentquestion.questions %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= frequentquestion.answer %>
  </p>

</div>

app/views/frequentquestions/edit.html.erb
<h1>Editing frequentquestion</h1>

<%= render "form", frequentquestion: @frequentquestion%>

<br>

<div>
  <%= link_to "Show this frequentquestion", @frequentquestion %> |
  <%= link_to "Back to frequentquestions", frequentquestions_path %>
</div>

app/views/frequentquestions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>FrequentquestionsINDEX</h1>

<div id="frequentquestions">
  <% @frequentquestions.each do |frequentquestion| %>
    <%= render frequentquestion %>
    <p>
    <% if current_admin %>
      <%= link_to "Editar", frequentquestion %> 
    <%end%>
    </p>
  <% end %>
</div>

app/views/frequentquestions/new.html.erb
<h1>New frequentquestion</h1>
<%= render "form", frequentquestion: @frequentquestion %>

app/views/frequentquestions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @frequentquestion %>

<div>
  <%= link_to "Edit this frequentquestion", edit_frequentquestion_path(@frequentquestion) %> |
  <%= link_to "Back to frequentquestions", frequentquestions_path %>

  <%= button_to "Destroy this frequentquestion", @frequentquestion, method: :delete %>
</div>