config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get 'admin/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :admins, controllers: {sessions: 'admins/sessions'}


  resources :frequentquestions
    
end

app/views/admin/_navbar.html.erb
<div id="head-nav" class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-right user-nav">
      <li class="dropdown profile_menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <!-- <span><%= current_admin.email %></span> -->
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to 'My Account ', method: :delete %>
          </li>
          <li>
            <%= link_to 'Profile ', method: :delete %>
          </li>
          <li>
            <%= link_to 'Messages ', method: :delete %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Cerrar Sesion", destroy_admin_session_path %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/admin/_sidebar.html.erb
<div class="cl-sidebar">
<div class="cl-toggle">
    <i class="fa fa-bars"></i>
</div>
<div class="cl-navblock">
    <div class="menu-space">
    <div class="content">
        <%= link_to root_path do %>
        <div class="sidebar-logo">
        <div class="logo text-center">
        <div class="row">
        <div class="col-lg-12 hidden-sm hidden-xs">
            <%= image_tag 'logo-light.png', class: "logo-cms" %>
        </div>
        <div class="hidden-lg hidden-md visible-xs-12">
            <%= image_tag '', class: "logo-mini"%>
        </div>
    </div>
    </div>
        </div>
        <% end %>
             <ul class="cl-vnavigation">
            <li><a href="/" target="_blank"><i class="fa fa-chrome"></i><span>Ver pagina web</span></a>
            </li>
            <li><a href="#"><i class="fa fa-circle"></i><span>Categoria</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle"></i><span>Sub categoria</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-product-hunt"></i><span>Productos</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
              
            </li>
            <li><a href="#"><i class="fa fa-question"></i><span>Preguntas frecuentes</span></a>
              <ul class="sub-menu">
                <li><%= link_to 'Ver', frequentquestions_path,  class:'' %></span></a></li>

                </ul>
            </li>
            <li><a href="#"><i class="fa fa-id-card-o"></i><span>Sobre nosotros</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-envelope-open-o"></i><span>Contacto</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-user-circle"></i><span>Usuarios</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-usd"></i><span>Ventas</span></a>
              <ul class="sub-menu">
                <li><a href="layout-boxed.html"><span class="label label-primary pull-right">New</span>Boxed Layout</a></li>
                <li><a href="layout-topbar.html"><span class="label label-primary pull-right">New</span>Top Menu</a></li>
              </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>